# Generated by Django 6.1 on 2026-08-29 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='User Name may contain only Latin letters and digits.', regex='^[A-Za-z0-9]+$')])),
                ('email', models.EmailField(max_length=254)),
                ('home_page', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='comments_co_created_f3c0a0_idx'), models.Index(fields=['author_name'], name='comments_co_author__c8630d_idx'), models.Index(fields=['email'], name='comments_co_email_7ec44a_idx')],
            },
        ),
    ]
